### ISSUE TITLE
Run on multiple GPU

### ISSUE THREAD

**Issue by hiral-kotadiya** [serengil/retinaface#40]
How can we run retina face on multiple GPU?

**Comment by serengil** [comment]
if you install tensorflow-gpu before installing deepface, that package will handle it.

**Comment by csmailis** [comment]
After you install tensorflow GPU you can use the following command within the python script that executes RetinaFace to:
1. os.environ["CUDA_VISIBLE_DEVICES"] = "1"  **- > Specify which GPU to use**
2. os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'  ->  **- > Limit the amount of reserved VRAM so that other scripts can be run in the same GPU as well**
